name:                harcat
version:             0.1.0.0
github:              c000/harcat
license:             BSD3
author:              c000
maintainer:          example@example.com
copyright:           2019 c000

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/c000/harcat#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.7.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - base64-bytestring
  - errors
  - microlens-platform
  - pipes
  - pipes-bytestring
  - stache
  - text
  - vector

executables:
  harcat:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - harcat
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts

tests:
  harcat-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - harcat
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
